name: Check large files

on: [push, pull_request]

jobs:
  check-large-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find large files
        run: |
          threshold_mb=5
          echo "Searching for files >= ${threshold_mb}MB"
          find . -type f -not -path './.git/*' -printf "%s %p\n" | awk -v t=$((threshold_mb*1024*1024)) '$1>=t {printf("%.2f MB %s\n", $1/1024/1024, $2)}' > large-files.txt || true
          if [ -s large-files.txt ]; then
            echo "Large files detected:" && cat large-files.txt
            exit 1
          fi
