name: Smoke test post-deploy

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-socketio
      - name: Run HTTP health check
        run: |
          python tools/socketio_smoke_check.py --http "${{ secrets.CREWAI_HEALTH_URL }}" --socket "${{ secrets.CREWAI_SOCKET_URL }}"
        env:
          CREWAI_HEALTH_URL: ${{ secrets.CREWAI_HEALTH_URL }}
          CREWAI_SOCKET_URL: ${{ secrets.CREWAI_SOCKET_URL }}
*** End Patch
